apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: fiap-hackaton
data:
  host: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xLmZpYXAtaGFja2F0b24uc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mi8=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: fiap-hackaton
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: host
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  connectionString: c2VydmVyPW15c3FsLWRlbW8uZmlhcC1oYWNrYXRvbi5zdmMuY2x1c3Rlci5sb2NhbDsgUG9ydD0zMzA2OyBEYXRhYmFzZT10ZXN0OyBVaWQ9dGVzdF91c2VyOyBQd2Q9dGVzdF9wYXNzd29yZDs=